[package]
name = "bulla"
version = "0.1.0"
edition = "2021"
author = "Aleksandr Medvedev"

[dependencies]
spin = "0.9.8"
bootloader = "0.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

